"""
Fetches Last.fm listener and playcount data for a list of songs.
Input: data/songs.csv (title, artist) — generated by score.py from Billboard/Spotify data.
Output: data/lastfm_raw.csv
"""

import requests
import pandas as pd
import time
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import LAST_FM_API_KEY

SONGS_INPUT = os.path.join(os.path.dirname(__file__), "../data/songs.csv")
OUTPUT = os.path.join(os.path.dirname(__file__), "../data/lastfm_raw.csv")
BASE_URL = "https://ws.audioscrobbler.com/2.0/"
SLEEP_BETWEEN = 0.25


def fetch_track(title, artist):
    resp = requests.get(BASE_URL, params={
        "method": "track.getInfo",
        "artist": artist,
        "track": title,
        "api_key": LAST_FM_API_KEY,
        "format": "json",
    }, timeout=10)
    data = resp.json()
    if "error" in data:
        return None
    track = data.get("track", {})
    return {
        "title": title,
        "artist": artist,
        "listeners": int(track.get("listeners", 0)),
        "playcount": int(track.get("playcount", 0)),
    }


def fetch_all():
    if not os.path.exists(SONGS_INPUT):
        print(f"ERROR: {SONGS_INPUT} not found. Run score.py --songs-only first.")
        return

    songs = pd.read_csv(SONGS_INPUT)
    existing = pd.read_csv(OUTPUT) if os.path.exists(OUTPUT) else pd.DataFrame()
    done_keys = set(zip(existing["title"], existing["artist"])) if not existing.empty else set()

    rows = []
    total = len(songs)

    for i, row in songs.iterrows():
        title, artist = row["title"], row["artist"]
        if (title, artist) in done_keys:
            continue

        result = fetch_track(title, artist)
        if result:
            rows.append(result)
            print(f"[{i+1}/{total}] {title} — {result['playcount']:,} plays")
        else:
            rows.append({"title": title, "artist": artist, "listeners": 0, "playcount": 0})
            print(f"[{i+1}/{total}] {title} — not found on Last.fm")

        time.sleep(SLEEP_BETWEEN)

        if len(rows) % 100 == 0:
            _save(existing, rows)
            existing = pd.read_csv(OUTPUT)
            rows = []
            done_keys = set(zip(existing["title"], existing["artist"]))

    _save(existing, rows)
    print(f"\nDone. Saved to {OUTPUT}")


def _save(existing, new_rows):
    if not new_rows:
        return
    new_df = pd.DataFrame(new_rows)
    combined = pd.concat([existing, new_df], ignore_index=True) if not existing.empty else new_df
    combined.to_csv(OUTPUT, index=False)


if __name__ == "__main__":
    fetch_all()
